DROP TABLE BOOKMARK;
DROP TABLE PURCHASE;
DROP TABLE DYNABOOKCOMMENT;
DROP TABLE BACKGROUND;
DROP TABLE EMOTION;
DROP TABLE DYNABOOKPART;
DROP TABLE DYNABOOK;
DROP TABLE DYNABOOKUSER;

DROP SEQUENCE dynabookusernumber_seq;
DROP SEQUENCE dynabook_seq;
DROP SEQUENCE dynabookpart_seq;
DROP SEQUENCE comment_seq;


create SEQUENCE dynabookusernumber_seq START WITH 1000;
create SEQUENCE dynabook_seq START WITH 1000;
create SEQUENCE dynabookpart_seq START WITH 1000;
create SEQUENCE comment_seq START WITH 1000;


CREATE TABLE DYNABOOKUSER(
    USERNUMBER NUMBER PRIMARY KEY
    ,NAME VARCHAR2(50) NOT NULL
    ,EMAIL VARCHAR2(200) NOT NULL UNIQUE
    ,NICK VARCHAR2(50) NOT NULL
    ,PW VARCHAR2(500) NOT NULL
    ,USERINPUTDATE DATE DEFAULT SYSDATE
    ,AUTHORITY VARCHAR2(30) DEFAULT 'MEMBER'
    ,SEX VARCHAR2(10)
    ,AGE NUMBER
    ,ACCOUNT_BALANCE NUMBER DEFAULT 0
);
CREATE TABLE DYNABOOK(
    BOOKNUMBER NUMBER PRIMARY KEY
    ,TITLE VARCHAR2(300) NOT NULL
    ,PENNAME VARCHAR2(50) NOT NULL
    ,SUBTITLE VARCHAR2(100)
    ,BOOKDATE DATE DEFAULT SYSDATE
    ,GENRE VARCHAR2(30) NOT NULL
    ,INTRODUCE VARCHAR2(2000) NOT NULL
    ,BOOK_USERNUMBER NUMBER
    
    ,CONSTRAINT FK_USERNUMBER_BOOK FOREIGN KEY (BOOK_USERNUMBER) REFERENCES DYNABOOKUSER(USERNUMBER)
);
CREATE TABLE DYNABOOKPART(
    BOOKPARTNUMBER NUMBER PRIMARY KEY
    ,EPISODE NUMBER NOT NULL
    ,EPISODETITLE VARCHAR2(500) NOT NULL
    ,TEXT CLOB NOT NULL
    ,PRICE NUMBER DEFAULT 0
    ,BOOKPARTDATE DATE DEFAULT SYSDATE
    ,HITS NUMBER DEFAULT 0
    ,PART_BOOKNUMBER NUMBER
    ,WRITERCOMMENT VARCHAR2(1000)
    
    ,CONSTRAINT FR_BOOKNUMBER_BOOKPART FOREIGN KEY (PART_BOOKNUMBER) REFERENCES DYNABOOK(BOOKNUMBER)
);
CREATE TABLE EMOTION(
    EMOTION_BOOKPARTNUMBER NUMBER
    ,PAGENUMBER NUMBER NOT NULL
    ,ANGER FLOAT NOT NULL
    ,DISGUST FLOAT NOT NULL
    ,FEAR FLOAT NOT NULL
    ,JOY FLOAT NOT NULL
    ,SADNESS FLOAT NOT NULL
    
     ,CONSTRAINT FR_BOOKPARTNUMBER_EMOTION FOREIGN KEY (EMOTION_BOOKPARTNUMBER) REFERENCES DYNABOOKPART(BOOKPARTNUMBER)
);
CREATE TABLE BACKGROUND(
    BACKGROUND_BOOKPARTNUMBER NUMBER
    ,PAGENUMBER NUMBER NOT NULL
    ,KEYWORD VARCHAR2(1000) NOT NULL
    
    ,CONSTRAINT FR_BOOKPARTNUMBER_BACKGROUND FOREIGN KEY (BACKGROUND_BOOKPARTNUMBER) REFERENCES DYNABOOKPART(BOOKPARTNUMBER)
);
CREATE TABLE DYNABOOKCOMMENT(
    COMMENTNUMBER NUMBER PRIMARY KEY
    ,USERCOMMENT VARCHAR2(1000) NOT NULL
    ,HITS NUMBER DEFAULT 0
    ,COMMENTDATE DATE DEFAULT SYSDATE
    ,COMMENT_BOOKPARTNUMBER NUMBER
    ,COMMENT_USERNUMBER NUMBER
    
    ,CONSTRAINT FR_BOOKPARTNUMBER_COMMENT FOREIGN KEY (COMMENT_BOOKPARTNUMBER) REFERENCES DYNABOOKPART(BOOKPARTNUMBER)
    ,CONSTRAINT FR_USERNUMBER_COMMENT FOREIGN KEY (COMMENT_USERNUMBER) REFERENCES DYNABOOKUSER(USERNUMBER)
);
CREATE TABLE PURCHASE(
    PURCHASE_USERNUMBER NUMBER
    ,PURCHASE_BOOKPARTNUMBER NUMBER
    ,PURCHASEDATE DATE DEFAULT SYSDATE
    
    ,CONSTRAINT FR_BOOKPARTNUMBER_PURCHASE FOREIGN KEY (PURCHASE_BOOKPARTNUMBER) REFERENCES DYNABOOKPART(BOOKPARTNUMBER)
    ,CONSTRAINT FR_USERNUMBER_PURCHASE FOREIGN KEY (PURCHASE_USERNUMBER) REFERENCES DYNABOOKUSER(USERNUMBER)
);
CREATE TABLE BOOKMARK(
    BOOKMARK_USERNUMBER NUMBER
    ,BOOKMARK_BOOKPARTNUMBER NUMBER
    ,BOOKMARKDATE DATE DEFAULT SYSDATE
    
    ,CONSTRAINT FR_BOOKPARTNUMBER_BOOKMARK FOREIGN KEY (BOOKMARK_BOOKPARTNUMBER) REFERENCES DYNABOOKPART(BOOKPARTNUMBER)
    ,CONSTRAINT FR_USERNUMBER_BOOKMARK FOREIGN KEY (BOOKMARK_USERNUMBER) REFERENCES DYNABOOKUSER(USERNUMBER)
);

